### ISSUE TITLE
Things todo for workshop

### ISSUE THREAD

**Issue by natbutter** [Sydney-Informatics-Hub/training.alphafold#32]
- [x] Upload example pbs scripts
- [x] Upload example data (fasta files)
- [ ] Bundle with release
- [x] Document out-of-workshop workflow

**Comment by natbutter** [comment]
Files to bundle:
```
example.pbd
alpha_job.pbs
input.fasta
```

For colab/singularity
```
alpha_build.pbs
alpha_sing.pbs
colab.img
```
